Update popover component
gliff-ai/style pull request #167
Opened 2022-04-14 11:02 UTC by ChrisBaidoo

## Description

Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).

Don't forget to reference all other pull requests which are associated to this one below: e.g.

closes #(issue-number)
relates gliff-ai/(repository-name)#(issue-number)

## Dependency Changes (delete if not applicable)

List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or package-lock.json been updated?

## Testing (delete if not applicable)

Please describe the new tests that have been added for this change along with any additional instructions required to reproduce a successful test and/or a list of any relevant details for your test configuration.

## Documentation (delete if not applicable)

Please describe the new documentation that has been added for this change (is there new user documentation? is there new developer documentation? is the developer documentation purely generated from docstrings in the code?).

## Database Changes (delete if not applicable)

Have any database changes been committed as part of this pull request?

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-04-15 08:02 UTC, ChasNelson1990 commented
Can we put a standalone version on the example page? So we have clarity that its separate?

2022-04-15 13:08 UTC, philipjackson approved these changes

2022-04-18 12:43 UTC, joshuajames-smith requested changes
<img width="758" alt="Screenshot 2022-04-18 at 13 31 24" src="https://user-images.githubusercontent.com/83074763/163808970-90cca552-6253-480d-9b3a-9f7b52053908.png">

It looks like we add a border to the green bar but this seems ignored by, what I assume is, the border radius. A little dive into the code and there is a border radius on the parent div (white box) but not on the child div (green box) – excuse the bad coding language. Could this be fixed so the border matches the border radius?

Could we also try the heading font ("Example Card") at size 18px and weight 500? Just as a move towards matching my designs to the design system.

2022-04-19 12:55 UTC, joshuajames-smith requested changes
A couple more changes which would help start to align the UI from it's current style to it's final style:

- [x] `border-radius: 6px` for the whole UI element (`class= css-1cov2rx`)
- [x] `border-radius: 6px 6px 0px 0px` for the green box UI element (`class= css-7zx1ao`)
- [ ] `padding: 8px 16px` for the green box UI element (`class= css-7zx1ao`)
- [ ] `padding: 12px 16px 14px` for the white box UI element (`class= css-e05fhr`)

-------------


<img width="610" alt="Screenshot 2022-04-19 at 10 59 37" src="https://user-images.githubusercontent.com/83074763/163981381-d7ebae58-ea4b-40a8-a07b-df6cea81e18c.png">
<img width="610" alt="Screenshot 2022-04-19 at 10 44 38" src="https://user-images.githubusercontent.com/83074763/163976889-d17ba2ea-9d79-48ba-b429-bf1924a16994.png">

2022-04-19 14:40 UTC, joshuajames-smith approved these changes

2022-04-19 17:10 UTC, joshuajames-smith approved these changes

2022-04-20 08:33 UTC, cooper667 approved these changes

2022-04-20 08:33 UTC, merged