feat: Add icon to the IconButton's tooltip
gliff-ai/style pull request #239
Opened 2022-06-23 15:34 UTC by SilviaZeta

## Description
Add an icon at the end of the `IconButton`'s tooltip and update the example page.

relates to https://github.com/gliff-ai/roadmap/issues/82

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-06-23 15:59 UTC, joshuajames-smith requested changes
**Current Design:**

<img height="80" alt="Screenshot 2022-06-23 at 16 51 50" src="https://user-images.githubusercontent.com/83074763/175342254-ec614538-75f3-406e-8c27-d46e847b0910.png"> <img height="80" alt="Screenshot 2022-06-23 at 16 52 05" src="https://user-images.githubusercontent.com/83074763/175342259-20aaada5-d652-413f-851b-e85c6bdd0d34.png">

**Intended Design:**

<img height="120" alt="Screenshot 2022-06-23 at 16 57 16" src="https://user-images.githubusercontent.com/83074763/175342948-e11e55a1-1866-4e2f-9eca-3790e63390c6.png">

---

- [ ] The height of the tooltip w/ status is much larger than the tooltip w/ shortcut. This will be the padding. The height of these 2 components height should be the same.

2022-06-24 10:00 UTC, joshuajames-smith requested changes
- [x] Could we change the CSS of the beta/alpha icon to `height:24px;`?
- [x] Tooltip text should also always be on one line - see below.
<img width="281" alt="Screenshot 2022-06-24 at 10 59 57" src="https://user-images.githubusercontent.com/83074763/175512497-c422ca59-d9ac-465f-b6c9-1a9c6f95598b.png">

2022-06-24 10:44 UTC, joshuajames-smith requested changes
- [ ] Not sure what has happened but the circle keyboard shortcuts have been stretched? Can we fix this?
<img width="428" alt="Screenshot 2022-06-24 at 11 43 48" src="https://user-images.githubusercontent.com/83074763/175519291-d6605792-9a60-40c9-b325-a8f51cd62bbc.png">

2022-06-24 13:32 UTC, joshuajames-smith approved these changes

2022-07-12 16:00 UTC, joshuajames-smith approved these changes

2022-07-12 16:41 UTC, ChrisBaidoo approved these changes

2022-07-12 16:55 UTC, merged