More stories
gliff-ai/style pull request #243
Opened 2022-06-28 20:56 UTC by ChrisBaidoo

## Description

Create stories for Dialog, Button, Logo, Popover, Datagrid and LoadingSpinner. 

closes #104 #111

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [x] I have read the gliff.ai Contribution Guide.
- [x] I have requested to **pull a branch** and not from main.
- [x] I have checked all commit message styles match the requested structure.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-06-30 14:46 UTC, joshuajames-smith requested changes
**BUTTON:**
On all buttons, can we change the CSS to:
- [x] weight: 400
- [x] border-radius: 6px
- [x] letter-spacing: 0
- [x] font-size: 0.9375rem / 15px
- [x] padding: 7px 20px

On the disabled primary and secondary button, can we change the CSS to:

- [x] background-colour: rgb(226, 226, 226)
- [x] [text] color: rgb(89, 89, 89)

On the outline button, can we change the CSS to:

- [x] border: 1px
- [x] border-color: rgb(187, 187, 187)
- [x] [text] color: rgb(187, 187, 187)

**DIALOGUE:**
On all dialogues, can we change the CSS to:

- [ ] border-radius: 8px 

Can we also make the following changes:

- [x] Use the spelling `Dialogue`
- [ ] Ensure buttons don't use shadows

**DIALOGUES + POPOVER:**

On all dialogues and popovers, can we change the CSS to:

- [ ] white box > border: 1px solid rgb(217, 221, 233)

Can we also make the following change:

- [x] Move the cross icon closer to the right end

^ _Current vs. Intended:_
<img height="120" alt="Screenshot 2022-06-30 at 15 45 36" src="https://user-images.githubusercontent.com/83074763/176707033-a811769c-e4e2-4b51-82b9-368b9cea0857.png"> <img height="120" alt="Screenshot 2022-06-30 at 15 46 11" src="https://user-images.githubusercontent.com/83074763/176707189-f4f94362-1c85-4c74-b2e7-47ba5b02444a.png">

2022-07-06 12:16 UTC, joshuajames-smith requested changes
<img width="260" alt="Screenshot 2022-07-06 at 12 34 56" src="https://user-images.githubusercontent.com/83074763/177541250-5bee4bcf-13f4-489d-bf2e-9c746acd029e.png"> <img width="260" alt="Screenshot 2022-07-06 at 12 32 56" src="https://user-images.githubusercontent.com/83074763/177540897-e168b7e7-c94c-4eb7-87f4-c21f9d8953cb.png">

- [ ] The outline for the green or purple topbar within card, dialogue or popover should not be a grey border but rather a darker green (#02E098) and darker purple (#9F6DEA) respectively.

<img width="260" alt="Screenshot 2022-07-06 at 12 39 06" src="https://user-images.githubusercontent.com/83074763/177541879-ce783978-08a5-4c1e-a373-6d76f39efdaf.png"> <img width="260" alt="Screenshot 2022-07-06 at 12 40 09" src="https://user-images.githubusercontent.com/83074763/177542030-132d9cb5-1586-452b-8fcb-7711019ca7b0.png">

- [ ] The `close` or `pin` icon when active should not change the height of the topbar within card, dialogue or popover.

2022-07-06 16:24 UTC, joshuajames-smith approved these changes

2022-07-07 08:11 UTC, SilviaZeta approved these changes

2022-07-08 07:32 UTC, merged