feat: Add feedback
gliff-ai/style pull request #256
Opened 2022-07-21 08:43 UTC by SilviaZeta

## Description
- turn the generic buttons in the `Dialogue` component into functional 'cancel' and 'confirm' buttons
- add new `Notepad` component for entering multiline text input 
- add old `Card` and `Dialog` components back in, to be able to work on latest version of style, before having to replace all instances of the old components in all the other repos.

relates to gliff-ai/annotate#774

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-07-21 08:49 UTC, ChasNelson1990 requested changes
Can we have a 1-to-1 about this. We should not reintroduce duplicate components. We should remove the incorrect components downstream instead.

2022-07-22 13:38 UTC, ChasNelson1990 submitted a review, later dismissed

2022-07-22 14:27 UTC, ChasNelson1990 approved these changes

2022-07-22 14:44 UTC, joshuajames-smith approved these changes

2022-07-22 14:45 UTC, merged